name: Plan Terraform
on: push
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_wrapper: false
      - run: terraform init
        working-directory: github
      - run: terraform plan -detailed-exitcode
        working-directory: github
        env:
          TF_VAR_GITHUB_TOKEN: ${{ secrets.GH_PAT_FOR_TERRAFORM_PLAN }}
